import type { Metadata } from 'next';
import { Grid } from '@mui/material';
import { Providers } from '@/providers/Providers';
import { createClient } from '@/services/supabase/server';
import Footer from '@/components/layouts/Footer';
import Header from '@/components/layouts/Header';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function RootProvidersWrapper({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  const user = data?.user ?? null;

  return <Providers initialUser={user}>{children}</Providers>;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta name='color-scheme' content='light dark' />
        <meta name='theme-color' content='#ffffff' />
      </head>
      <body>
        <RootProvidersWrapper>
          <Grid container direction='column' minHeight='60vh'>
            <Header />
            {children}
            <Footer />
          </Grid>
        </RootProvidersWrapper>
      </body>
    </html>
  );
}
